name = "r2-image-host"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
R2_PUBLIC_DOMAIN = "https://imgs.quickso.cn"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "INDEXES_KV"
id = "a4e550b84d3d478886c5cb9153a561c0"
preview_id = "a4e550b84d3d478886c5cb9153a561c0"

# R2 存储桶绑定
[[r2_buckets]]
binding = "bucket-binding"
bucket_name = "image-sharer"


[site]
bucket = "src/static"

